
namespace VehicleServiceManagement.ReportsInteraction
{
    partial class ContentInteractionPanel
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ContentInteractionPanel));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.TextBoxPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ButtonDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.LabelTotalSum = new Bunifu.UI.WinForms.BunifuLabel();
            this.TextBoxTotalSum = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LabelPrice = new Bunifu.UI.WinForms.BunifuLabel();
            this.LabelQuantity = new Bunifu.UI.WinForms.BunifuLabel();
            this.LabelTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.ButtonCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.ButtonSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.TextBoxQuantity = new Bunifu.UI.WinForms.BunifuTextBox();
            this.TextBoxTitle = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LabelHeader = new Bunifu.UI.WinForms.BunifuLabel();
            this.Notification = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Silver;
            this.bunifuPanel1.BorderRadius = 28;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.TextBoxPrice);
            this.bunifuPanel1.Controls.Add(this.ButtonDelete);
            this.bunifuPanel1.Controls.Add(this.LabelTotalSum);
            this.bunifuPanel1.Controls.Add(this.TextBoxTotalSum);
            this.bunifuPanel1.Controls.Add(this.LabelPrice);
            this.bunifuPanel1.Controls.Add(this.LabelQuantity);
            this.bunifuPanel1.Controls.Add(this.LabelTitle);
            this.bunifuPanel1.Controls.Add(this.ButtonCancel);
            this.bunifuPanel1.Controls.Add(this.ButtonSave);
            this.bunifuPanel1.Controls.Add(this.TextBoxQuantity);
            this.bunifuPanel1.Controls.Add(this.TextBoxTitle);
            this.bunifuPanel1.Controls.Add(this.LabelHeader);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(926, 307);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // TextBoxPrice
            // 
            this.TextBoxPrice.AcceptsReturn = false;
            this.TextBoxPrice.AcceptsTab = false;
            this.TextBoxPrice.AnimationSpeed = 200;
            this.TextBoxPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxPrice.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            this.TextBoxPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxPrice.BackgroundImage")));
            this.TextBoxPrice.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            this.TextBoxPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TextBoxPrice.BorderColorHover = System.Drawing.Color.White;
            this.TextBoxPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxPrice.BorderRadius = 5;
            this.TextBoxPrice.BorderThickness = 2;
            this.TextBoxPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxPrice.DefaultFont = new System.Drawing.Font("Segoe UI", 17F);
            this.TextBoxPrice.DefaultText = "";
            this.TextBoxPrice.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            this.TextBoxPrice.ForeColor = System.Drawing.Color.White;
            this.TextBoxPrice.HideSelection = true;
            this.TextBoxPrice.IconLeft = null;
            this.TextBoxPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxPrice.IconPadding = 10;
            this.TextBoxPrice.IconRight = null;
            this.TextBoxPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxPrice.Lines = new string[0];
            this.TextBoxPrice.Location = new System.Drawing.Point(189, 185);
            this.TextBoxPrice.MaxLength = 32767;
            this.TextBoxPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.TextBoxPrice.Modified = false;
            this.TextBoxPrice.Multiline = false;
            this.TextBoxPrice.Name = "TextBoxPrice";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxPrice.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TextBoxPrice.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.White;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxPrice.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxPrice.OnIdleState = stateProperties4;
            this.TextBoxPrice.Padding = new System.Windows.Forms.Padding(3);
            this.TextBoxPrice.PasswordChar = '\0';
            this.TextBoxPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxPrice.PlaceholderText = "50.00";
            this.TextBoxPrice.ReadOnly = false;
            this.TextBoxPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxPrice.SelectedText = "";
            this.TextBoxPrice.SelectionLength = 0;
            this.TextBoxPrice.SelectionStart = 0;
            this.TextBoxPrice.ShortcutsEnabled = true;
            this.TextBoxPrice.Size = new System.Drawing.Size(150, 47);
            this.TextBoxPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TextBoxPrice.TabIndex = 99;
            this.TextBoxPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.TextBoxPrice.TextMarginBottom = 0;
            this.TextBoxPrice.TextMarginLeft = 3;
            this.TextBoxPrice.TextMarginTop = 0;
            this.TextBoxPrice.TextPlaceholder = "50.00";
            this.TextBoxPrice.UseSystemPasswordChar = false;
            this.TextBoxPrice.WordWrap = true;
            this.TextBoxPrice.TextChanged += new System.EventHandler(this.TextBoxPrice_TextChanged_1);
            // 
            // ButtonDelete
            // 
            this.ButtonDelete.AllowAnimations = true;
            this.ButtonDelete.AllowMouseEffects = true;
            this.ButtonDelete.AllowToggling = false;
            this.ButtonDelete.AnimationSpeed = 200;
            this.ButtonDelete.AutoGenerateColors = false;
            this.ButtonDelete.AutoRoundBorders = false;
            this.ButtonDelete.AutoSizeLeftIcon = true;
            this.ButtonDelete.AutoSizeRightIcon = true;
            this.ButtonDelete.BackColor = System.Drawing.Color.Transparent;
            this.ButtonDelete.BackColor1 = System.Drawing.Color.Gray;
            this.ButtonDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ButtonDelete.BackgroundImage")));
            this.ButtonDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonDelete.ButtonText = "ИЗТРИЙ";
            this.ButtonDelete.ButtonTextMarginLeft = 0;
            this.ButtonDelete.ColorContrastOnClick = 45;
            this.ButtonDelete.ColorContrastOnHover = 45;
            this.ButtonDelete.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.ButtonDelete.CustomizableEdges = borderEdges1;
            this.ButtonDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ButtonDelete.DisabledBorderColor = System.Drawing.Color.Black;
            this.ButtonDelete.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ButtonDelete.DisabledForecolor = System.Drawing.Color.White;
            this.ButtonDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ButtonDelete.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.ButtonDelete.ForeColor = System.Drawing.Color.White;
            this.ButtonDelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ButtonDelete.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonDelete.IconLeftPadding = new System.Windows.Forms.Padding(10, 3, 3, 3);
            this.ButtonDelete.IconMarginLeft = 11;
            this.ButtonDelete.IconPadding = 10;
            this.ButtonDelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ButtonDelete.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonDelete.IconRightPadding = new System.Windows.Forms.Padding(3);
            this.ButtonDelete.IconSize = 25;
            this.ButtonDelete.IdleBorderColor = System.Drawing.Color.Black;
            this.ButtonDelete.IdleBorderRadius = 30;
            this.ButtonDelete.IdleBorderThickness = 1;
            this.ButtonDelete.IdleFillColor = System.Drawing.Color.Gray;
            this.ButtonDelete.IdleIconLeftImage = null;
            this.ButtonDelete.IdleIconRightImage = null;
            this.ButtonDelete.IndicateFocus = false;
            this.ButtonDelete.Location = new System.Drawing.Point(458, 251);
            this.ButtonDelete.Name = "ButtonDelete";
            this.ButtonDelete.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.ButtonDelete.OnDisabledState.BorderRadius = 30;
            this.ButtonDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonDelete.OnDisabledState.BorderThickness = 1;
            this.ButtonDelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ButtonDelete.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.ButtonDelete.OnDisabledState.IconLeftImage = null;
            this.ButtonDelete.OnDisabledState.IconRightImage = null;
            this.ButtonDelete.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.ButtonDelete.onHoverState.BorderRadius = 30;
            this.ButtonDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonDelete.onHoverState.BorderThickness = 1;
            this.ButtonDelete.onHoverState.FillColor = System.Drawing.Color.Red;
            this.ButtonDelete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ButtonDelete.onHoverState.IconLeftImage = null;
            this.ButtonDelete.onHoverState.IconRightImage = null;
            this.ButtonDelete.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.ButtonDelete.OnIdleState.BorderRadius = 30;
            this.ButtonDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonDelete.OnIdleState.BorderThickness = 1;
            this.ButtonDelete.OnIdleState.FillColor = System.Drawing.Color.Gray;
            this.ButtonDelete.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ButtonDelete.OnIdleState.IconLeftImage = null;
            this.ButtonDelete.OnIdleState.IconRightImage = null;
            this.ButtonDelete.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.ButtonDelete.OnPressedState.BorderRadius = 30;
            this.ButtonDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonDelete.OnPressedState.BorderThickness = 1;
            this.ButtonDelete.OnPressedState.FillColor = System.Drawing.Color.Gray;
            this.ButtonDelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ButtonDelete.OnPressedState.IconLeftImage = null;
            this.ButtonDelete.OnPressedState.IconRightImage = null;
            this.ButtonDelete.Size = new System.Drawing.Size(140, 44);
            this.ButtonDelete.TabIndex = 98;
            this.ButtonDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ButtonDelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ButtonDelete.TextMarginLeft = 0;
            this.ButtonDelete.TextPadding = new System.Windows.Forms.Padding(0);
            this.ButtonDelete.UseDefaultRadiusAndThickness = true;
            this.ButtonDelete.Visible = false;
            this.ButtonDelete.Click += new System.EventHandler(this.ButtonDelete_Click);
            // 
            // LabelTotalSum
            // 
            this.LabelTotalSum.AllowParentOverrides = false;
            this.LabelTotalSum.AutoEllipsis = false;
            this.LabelTotalSum.Cursor = System.Windows.Forms.Cursors.Default;
            this.LabelTotalSum.CursorType = System.Windows.Forms.Cursors.Default;
            this.LabelTotalSum.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.LabelTotalSum.ForeColor = System.Drawing.Color.White;
            this.LabelTotalSum.Location = new System.Drawing.Point(363, 156);
            this.LabelTotalSum.Name = "LabelTotalSum";
            this.LabelTotalSum.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LabelTotalSum.Size = new System.Drawing.Size(91, 23);
            this.LabelTotalSum.TabIndex = 97;
            this.LabelTotalSum.Text = "Обща сума";
            this.LabelTotalSum.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LabelTotalSum.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // TextBoxTotalSum
            // 
            this.TextBoxTotalSum.AcceptsReturn = false;
            this.TextBoxTotalSum.AcceptsTab = false;
            this.TextBoxTotalSum.AnimationSpeed = 200;
            this.TextBoxTotalSum.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxTotalSum.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxTotalSum.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            this.TextBoxTotalSum.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxTotalSum.BackgroundImage")));
            this.TextBoxTotalSum.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            this.TextBoxTotalSum.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TextBoxTotalSum.BorderColorHover = System.Drawing.Color.White;
            this.TextBoxTotalSum.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxTotalSum.BorderRadius = 5;
            this.TextBoxTotalSum.BorderThickness = 2;
            this.TextBoxTotalSum.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxTotalSum.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTotalSum.DefaultFont = new System.Drawing.Font("Segoe UI", 17F);
            this.TextBoxTotalSum.DefaultText = "0.00 лв.";
            this.TextBoxTotalSum.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            this.TextBoxTotalSum.ForeColor = System.Drawing.Color.White;
            this.TextBoxTotalSum.HideSelection = true;
            this.TextBoxTotalSum.IconLeft = null;
            this.TextBoxTotalSum.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTotalSum.IconPadding = 10;
            this.TextBoxTotalSum.IconRight = null;
            this.TextBoxTotalSum.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTotalSum.Lines = new string[] {
        "0.00 лв."};
            this.TextBoxTotalSum.Location = new System.Drawing.Point(363, 185);
            this.TextBoxTotalSum.MaxLength = 32767;
            this.TextBoxTotalSum.MinimumSize = new System.Drawing.Size(1, 1);
            this.TextBoxTotalSum.Modified = false;
            this.TextBoxTotalSum.Multiline = false;
            this.TextBoxTotalSum.Name = "TextBoxTotalSum";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTotalSum.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TextBoxTotalSum.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.White;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTotalSum.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            stateProperties8.ForeColor = System.Drawing.Color.White;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTotalSum.OnIdleState = stateProperties8;
            this.TextBoxTotalSum.Padding = new System.Windows.Forms.Padding(3);
            this.TextBoxTotalSum.PasswordChar = '\0';
            this.TextBoxTotalSum.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxTotalSum.PlaceholderText = "";
            this.TextBoxTotalSum.ReadOnly = false;
            this.TextBoxTotalSum.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxTotalSum.SelectedText = "";
            this.TextBoxTotalSum.SelectionLength = 0;
            this.TextBoxTotalSum.SelectionStart = 8;
            this.TextBoxTotalSum.ShortcutsEnabled = true;
            this.TextBoxTotalSum.Size = new System.Drawing.Size(150, 47);
            this.TextBoxTotalSum.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TextBoxTotalSum.TabIndex = 96;
            this.TextBoxTotalSum.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.TextBoxTotalSum.TextMarginBottom = 0;
            this.TextBoxTotalSum.TextMarginLeft = 3;
            this.TextBoxTotalSum.TextMarginTop = 0;
            this.TextBoxTotalSum.TextPlaceholder = "";
            this.TextBoxTotalSum.UseSystemPasswordChar = false;
            this.TextBoxTotalSum.WordWrap = true;
            // 
            // LabelPrice
            // 
            this.LabelPrice.AllowParentOverrides = false;
            this.LabelPrice.AutoEllipsis = false;
            this.LabelPrice.Cursor = System.Windows.Forms.Cursors.Default;
            this.LabelPrice.CursorType = System.Windows.Forms.Cursors.Default;
            this.LabelPrice.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.LabelPrice.ForeColor = System.Drawing.Color.White;
            this.LabelPrice.Location = new System.Drawing.Point(189, 156);
            this.LabelPrice.Name = "LabelPrice";
            this.LabelPrice.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LabelPrice.Size = new System.Drawing.Size(42, 23);
            this.LabelPrice.TabIndex = 95;
            this.LabelPrice.Text = "Цена";
            this.LabelPrice.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LabelPrice.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // LabelQuantity
            // 
            this.LabelQuantity.AllowParentOverrides = false;
            this.LabelQuantity.AutoEllipsis = false;
            this.LabelQuantity.Cursor = System.Windows.Forms.Cursors.Default;
            this.LabelQuantity.CursorType = System.Windows.Forms.Cursors.Default;
            this.LabelQuantity.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.LabelQuantity.ForeColor = System.Drawing.Color.White;
            this.LabelQuantity.Location = new System.Drawing.Point(15, 156);
            this.LabelQuantity.Name = "LabelQuantity";
            this.LabelQuantity.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LabelQuantity.Size = new System.Drawing.Size(97, 23);
            this.LabelQuantity.TabIndex = 94;
            this.LabelQuantity.Text = "Количество";
            this.LabelQuantity.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LabelQuantity.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // LabelTitle
            // 
            this.LabelTitle.AllowParentOverrides = false;
            this.LabelTitle.AutoEllipsis = false;
            this.LabelTitle.Cursor = System.Windows.Forms.Cursors.Default;
            this.LabelTitle.CursorType = System.Windows.Forms.Cursors.Default;
            this.LabelTitle.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.LabelTitle.ForeColor = System.Drawing.Color.White;
            this.LabelTitle.Location = new System.Drawing.Point(14, 63);
            this.LabelTitle.Name = "LabelTitle";
            this.LabelTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LabelTitle.Size = new System.Drawing.Size(81, 23);
            this.LabelTitle.TabIndex = 93;
            this.LabelTitle.Text = "Описание";
            this.LabelTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.LabelTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // ButtonCancel
            // 
            this.ButtonCancel.AllowAnimations = true;
            this.ButtonCancel.AllowMouseEffects = true;
            this.ButtonCancel.AllowToggling = false;
            this.ButtonCancel.AnimationSpeed = 200;
            this.ButtonCancel.AutoGenerateColors = false;
            this.ButtonCancel.AutoRoundBorders = false;
            this.ButtonCancel.AutoSizeLeftIcon = true;
            this.ButtonCancel.AutoSizeRightIcon = true;
            this.ButtonCancel.BackColor = System.Drawing.Color.Transparent;
            this.ButtonCancel.BackColor1 = System.Drawing.Color.Gray;
            this.ButtonCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ButtonCancel.BackgroundImage")));
            this.ButtonCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonCancel.ButtonText = "ОТКАЖИ";
            this.ButtonCancel.ButtonTextMarginLeft = 0;
            this.ButtonCancel.ColorContrastOnClick = 45;
            this.ButtonCancel.ColorContrastOnHover = 45;
            this.ButtonCancel.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.ButtonCancel.CustomizableEdges = borderEdges2;
            this.ButtonCancel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ButtonCancel.DisabledBorderColor = System.Drawing.Color.Black;
            this.ButtonCancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ButtonCancel.DisabledForecolor = System.Drawing.Color.White;
            this.ButtonCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ButtonCancel.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.ButtonCancel.ForeColor = System.Drawing.Color.White;
            this.ButtonCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ButtonCancel.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ButtonCancel.IconMarginLeft = 11;
            this.ButtonCancel.IconPadding = 10;
            this.ButtonCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ButtonCancel.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ButtonCancel.IconSize = 25;
            this.ButtonCancel.IdleBorderColor = System.Drawing.Color.Black;
            this.ButtonCancel.IdleBorderRadius = 30;
            this.ButtonCancel.IdleBorderThickness = 1;
            this.ButtonCancel.IdleFillColor = System.Drawing.Color.Gray;
            this.ButtonCancel.IdleIconLeftImage = null;
            this.ButtonCancel.IdleIconRightImage = null;
            this.ButtonCancel.IndicateFocus = false;
            this.ButtonCancel.Location = new System.Drawing.Point(615, 251);
            this.ButtonCancel.Name = "ButtonCancel";
            this.ButtonCancel.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.ButtonCancel.OnDisabledState.BorderRadius = 30;
            this.ButtonCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonCancel.OnDisabledState.BorderThickness = 1;
            this.ButtonCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ButtonCancel.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.ButtonCancel.OnDisabledState.IconLeftImage = null;
            this.ButtonCancel.OnDisabledState.IconRightImage = null;
            this.ButtonCancel.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.ButtonCancel.onHoverState.BorderRadius = 30;
            this.ButtonCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonCancel.onHoverState.BorderThickness = 1;
            this.ButtonCancel.onHoverState.FillColor = System.Drawing.Color.SandyBrown;
            this.ButtonCancel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ButtonCancel.onHoverState.IconLeftImage = null;
            this.ButtonCancel.onHoverState.IconRightImage = null;
            this.ButtonCancel.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.ButtonCancel.OnIdleState.BorderRadius = 30;
            this.ButtonCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonCancel.OnIdleState.BorderThickness = 1;
            this.ButtonCancel.OnIdleState.FillColor = System.Drawing.Color.Gray;
            this.ButtonCancel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ButtonCancel.OnIdleState.IconLeftImage = null;
            this.ButtonCancel.OnIdleState.IconRightImage = null;
            this.ButtonCancel.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.ButtonCancel.OnPressedState.BorderRadius = 30;
            this.ButtonCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonCancel.OnPressedState.BorderThickness = 1;
            this.ButtonCancel.OnPressedState.FillColor = System.Drawing.Color.Gray;
            this.ButtonCancel.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.ButtonCancel.OnPressedState.IconLeftImage = null;
            this.ButtonCancel.OnPressedState.IconRightImage = null;
            this.ButtonCancel.Size = new System.Drawing.Size(140, 44);
            this.ButtonCancel.TabIndex = 91;
            this.ButtonCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ButtonCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ButtonCancel.TextMarginLeft = 0;
            this.ButtonCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.ButtonCancel.UseDefaultRadiusAndThickness = true;
            this.ButtonCancel.Click += new System.EventHandler(this.ButtonCancel_Click);
            // 
            // ButtonSave
            // 
            this.ButtonSave.AllowAnimations = true;
            this.ButtonSave.AllowMouseEffects = true;
            this.ButtonSave.AllowToggling = false;
            this.ButtonSave.AnimationSpeed = 200;
            this.ButtonSave.AutoGenerateColors = false;
            this.ButtonSave.AutoRoundBorders = false;
            this.ButtonSave.AutoSizeLeftIcon = true;
            this.ButtonSave.AutoSizeRightIcon = true;
            this.ButtonSave.BackColor = System.Drawing.Color.Transparent;
            this.ButtonSave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            this.ButtonSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ButtonSave.BackgroundImage")));
            this.ButtonSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonSave.ButtonText = "ЗАПАЗИ";
            this.ButtonSave.ButtonTextMarginLeft = 0;
            this.ButtonSave.ColorContrastOnClick = 45;
            this.ButtonSave.ColorContrastOnHover = 45;
            this.ButtonSave.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.ButtonSave.CustomizableEdges = borderEdges3;
            this.ButtonSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ButtonSave.DisabledBorderColor = System.Drawing.Color.Black;
            this.ButtonSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ButtonSave.DisabledForecolor = System.Drawing.Color.White;
            this.ButtonSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.ButtonSave.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.ButtonSave.ForeColor = System.Drawing.Color.White;
            this.ButtonSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ButtonSave.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ButtonSave.IconMarginLeft = 11;
            this.ButtonSave.IconPadding = 10;
            this.ButtonSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.ButtonSave.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.ButtonSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ButtonSave.IconSize = 25;
            this.ButtonSave.IdleBorderColor = System.Drawing.Color.Black;
            this.ButtonSave.IdleBorderRadius = 30;
            this.ButtonSave.IdleBorderThickness = 1;
            this.ButtonSave.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            this.ButtonSave.IdleIconLeftImage = null;
            this.ButtonSave.IdleIconRightImage = null;
            this.ButtonSave.IndicateFocus = false;
            this.ButtonSave.Location = new System.Drawing.Point(773, 251);
            this.ButtonSave.Name = "ButtonSave";
            this.ButtonSave.OnDisabledState.BorderColor = System.Drawing.Color.Black;
            this.ButtonSave.OnDisabledState.BorderRadius = 30;
            this.ButtonSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonSave.OnDisabledState.BorderThickness = 1;
            this.ButtonSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ButtonSave.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.ButtonSave.OnDisabledState.IconLeftImage = null;
            this.ButtonSave.OnDisabledState.IconRightImage = null;
            this.ButtonSave.onHoverState.BorderColor = System.Drawing.Color.Black;
            this.ButtonSave.onHoverState.BorderRadius = 30;
            this.ButtonSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonSave.onHoverState.BorderThickness = 1;
            this.ButtonSave.onHoverState.FillColor = System.Drawing.Color.LimeGreen;
            this.ButtonSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ButtonSave.onHoverState.IconLeftImage = null;
            this.ButtonSave.onHoverState.IconRightImage = null;
            this.ButtonSave.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.ButtonSave.OnIdleState.BorderRadius = 30;
            this.ButtonSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonSave.OnIdleState.BorderThickness = 1;
            this.ButtonSave.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            this.ButtonSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ButtonSave.OnIdleState.IconLeftImage = null;
            this.ButtonSave.OnIdleState.IconRightImage = null;
            this.ButtonSave.OnPressedState.BorderColor = System.Drawing.Color.Black;
            this.ButtonSave.OnPressedState.BorderRadius = 30;
            this.ButtonSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.ButtonSave.OnPressedState.BorderThickness = 1;
            this.ButtonSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            this.ButtonSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ButtonSave.OnPressedState.IconLeftImage = null;
            this.ButtonSave.OnPressedState.IconRightImage = null;
            this.ButtonSave.Size = new System.Drawing.Size(140, 44);
            this.ButtonSave.TabIndex = 92;
            this.ButtonSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ButtonSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ButtonSave.TextMarginLeft = 0;
            this.ButtonSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.ButtonSave.UseDefaultRadiusAndThickness = true;
            this.ButtonSave.Click += new System.EventHandler(this.ButtonSave_Click);
            // 
            // TextBoxQuantity
            // 
            this.TextBoxQuantity.AcceptsReturn = false;
            this.TextBoxQuantity.AcceptsTab = false;
            this.TextBoxQuantity.AnimationSpeed = 200;
            this.TextBoxQuantity.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxQuantity.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxQuantity.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            this.TextBoxQuantity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxQuantity.BackgroundImage")));
            this.TextBoxQuantity.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            this.TextBoxQuantity.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TextBoxQuantity.BorderColorHover = System.Drawing.Color.White;
            this.TextBoxQuantity.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxQuantity.BorderRadius = 5;
            this.TextBoxQuantity.BorderThickness = 2;
            this.TextBoxQuantity.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxQuantity.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxQuantity.DefaultFont = new System.Drawing.Font("Segoe UI", 17F);
            this.TextBoxQuantity.DefaultText = "";
            this.TextBoxQuantity.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            this.TextBoxQuantity.ForeColor = System.Drawing.Color.White;
            this.TextBoxQuantity.HideSelection = true;
            this.TextBoxQuantity.IconLeft = null;
            this.TextBoxQuantity.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxQuantity.IconPadding = 10;
            this.TextBoxQuantity.IconRight = null;
            this.TextBoxQuantity.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxQuantity.Lines = new string[0];
            this.TextBoxQuantity.Location = new System.Drawing.Point(15, 185);
            this.TextBoxQuantity.MaxLength = 32767;
            this.TextBoxQuantity.MinimumSize = new System.Drawing.Size(1, 1);
            this.TextBoxQuantity.Modified = false;
            this.TextBoxQuantity.Multiline = false;
            this.TextBoxQuantity.Name = "TextBoxQuantity";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxQuantity.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TextBoxQuantity.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.White;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxQuantity.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            stateProperties12.ForeColor = System.Drawing.Color.White;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxQuantity.OnIdleState = stateProperties12;
            this.TextBoxQuantity.Padding = new System.Windows.Forms.Padding(3);
            this.TextBoxQuantity.PasswordChar = '\0';
            this.TextBoxQuantity.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxQuantity.PlaceholderText = "1";
            this.TextBoxQuantity.ReadOnly = false;
            this.TextBoxQuantity.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxQuantity.SelectedText = "";
            this.TextBoxQuantity.SelectionLength = 0;
            this.TextBoxQuantity.SelectionStart = 0;
            this.TextBoxQuantity.ShortcutsEnabled = true;
            this.TextBoxQuantity.Size = new System.Drawing.Size(150, 47);
            this.TextBoxQuantity.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TextBoxQuantity.TabIndex = 89;
            this.TextBoxQuantity.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.TextBoxQuantity.TextMarginBottom = 0;
            this.TextBoxQuantity.TextMarginLeft = 3;
            this.TextBoxQuantity.TextMarginTop = 0;
            this.TextBoxQuantity.TextPlaceholder = "1";
            this.TextBoxQuantity.UseSystemPasswordChar = false;
            this.TextBoxQuantity.WordWrap = true;
            this.TextBoxQuantity.TextChanged += new System.EventHandler(this.TextBoxQuantity_TextChanged);
            // 
            // TextBoxTitle
            // 
            this.TextBoxTitle.AcceptsReturn = false;
            this.TextBoxTitle.AcceptsTab = false;
            this.TextBoxTitle.AnimationSpeed = 200;
            this.TextBoxTitle.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.TextBoxTitle.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.TextBoxTitle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            this.TextBoxTitle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("TextBoxTitle.BackgroundImage")));
            this.TextBoxTitle.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            this.TextBoxTitle.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.TextBoxTitle.BorderColorHover = System.Drawing.Color.White;
            this.TextBoxTitle.BorderColorIdle = System.Drawing.Color.Silver;
            this.TextBoxTitle.BorderRadius = 5;
            this.TextBoxTitle.BorderThickness = 2;
            this.TextBoxTitle.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.TextBoxTitle.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTitle.DefaultFont = new System.Drawing.Font("Segoe UI", 17F);
            this.TextBoxTitle.DefaultText = "";
            this.TextBoxTitle.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            this.TextBoxTitle.ForeColor = System.Drawing.Color.White;
            this.TextBoxTitle.HideSelection = true;
            this.TextBoxTitle.IconLeft = null;
            this.TextBoxTitle.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTitle.IconPadding = 10;
            this.TextBoxTitle.IconRight = null;
            this.TextBoxTitle.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.TextBoxTitle.Lines = new string[0];
            this.TextBoxTitle.Location = new System.Drawing.Point(14, 92);
            this.TextBoxTitle.MaxLength = 32767;
            this.TextBoxTitle.MinimumSize = new System.Drawing.Size(1, 1);
            this.TextBoxTitle.Modified = false;
            this.TextBoxTitle.Multiline = false;
            this.TextBoxTitle.Name = "TextBoxTitle";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTitle.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.TextBoxTitle.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.White;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTitle.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.TextBoxTitle.OnIdleState = stateProperties16;
            this.TextBoxTitle.Padding = new System.Windows.Forms.Padding(3);
            this.TextBoxTitle.PasswordChar = '\0';
            this.TextBoxTitle.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.TextBoxTitle.PlaceholderText = "Въведете описание";
            this.TextBoxTitle.ReadOnly = false;
            this.TextBoxTitle.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.TextBoxTitle.SelectedText = "";
            this.TextBoxTitle.SelectionLength = 0;
            this.TextBoxTitle.SelectionStart = 0;
            this.TextBoxTitle.ShortcutsEnabled = true;
            this.TextBoxTitle.Size = new System.Drawing.Size(888, 47);
            this.TextBoxTitle.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.TextBoxTitle.TabIndex = 88;
            this.TextBoxTitle.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.TextBoxTitle.TextMarginBottom = 0;
            this.TextBoxTitle.TextMarginLeft = 3;
            this.TextBoxTitle.TextMarginTop = 0;
            this.TextBoxTitle.TextPlaceholder = "Въведете описание";
            this.TextBoxTitle.UseSystemPasswordChar = false;
            this.TextBoxTitle.WordWrap = true;
            // 
            // LabelHeader
            // 
            this.LabelHeader.AllowParentOverrides = false;
            this.LabelHeader.AutoEllipsis = false;
            this.LabelHeader.AutoSize = false;
            this.LabelHeader.Cursor = System.Windows.Forms.Cursors.Default;
            this.LabelHeader.CursorType = System.Windows.Forms.Cursors.Default;
            this.LabelHeader.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.LabelHeader.ForeColor = System.Drawing.Color.White;
            this.LabelHeader.Location = new System.Drawing.Point(0, 3);
            this.LabelHeader.Name = "LabelHeader";
            this.LabelHeader.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.LabelHeader.Size = new System.Drawing.Size(980, 48);
            this.LabelHeader.TabIndex = 48;
            this.LabelHeader.Text = "ДОБАВЯНЕ НА АРТИКУЛ";
            this.LabelHeader.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.LabelHeader.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Notification
            // 
            this.Notification.AllowDragging = false;
            this.Notification.AllowMultipleViews = true;
            this.Notification.ClickToClose = true;
            this.Notification.DoubleClickToClose = true;
            this.Notification.DurationAfterIdle = 3000;
            this.Notification.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Notification.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Notification.ErrorOptions.ActionBorderRadius = 1;
            this.Notification.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Notification.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Notification.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.Notification.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.Notification.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.Notification.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.Notification.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.Notification.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.Notification.ErrorOptions.IconLeftMargin = 12;
            this.Notification.FadeCloseIcon = false;
            this.Notification.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.Notification.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            this.Notification.InformationOptions.ActionBorderColor = System.Drawing.Color.White;
            this.Notification.InformationOptions.ActionBorderRadius = 25;
            this.Notification.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Notification.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Notification.InformationOptions.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            this.Notification.InformationOptions.BorderColor = System.Drawing.Color.Black;
            this.Notification.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.Notification.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.Notification.InformationOptions.ForeColor = System.Drawing.Color.White;
            this.Notification.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.Notification.InformationOptions.IconLeftMargin = 12;
            this.Notification.Margin = 40;
            this.Notification.MaximumSize = new System.Drawing.Size(0, 0);
            this.Notification.MaximumViews = 1;
            this.Notification.MessageRightMargin = 10;
            this.Notification.MinimumSize = new System.Drawing.Size(0, 0);
            this.Notification.ShowBorders = true;
            this.Notification.ShowCloseIcon = false;
            this.Notification.ShowIcon = true;
            this.Notification.ShowShadows = true;
            this.Notification.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            this.Notification.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Notification.SuccessOptions.ActionBorderRadius = 25;
            this.Notification.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Notification.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Notification.SuccessOptions.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            this.Notification.SuccessOptions.BorderColor = System.Drawing.Color.Gray;
            this.Notification.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.Notification.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.Notification.SuccessOptions.ForeColor = System.Drawing.Color.White;
            this.Notification.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.Notification.SuccessOptions.IconLeftMargin = 12;
            this.Notification.ViewsMargin = 1;
            this.Notification.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(216)))), ((int)(((byte)(172)))));
            this.Notification.WarningOptions.ActionBorderColor = System.Drawing.Color.White;
            this.Notification.WarningOptions.ActionBorderRadius = 25;
            this.Notification.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.Notification.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.Notification.WarningOptions.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(61)))), ((int)(((byte)(81)))));
            this.Notification.WarningOptions.BorderColor = System.Drawing.Color.Gray;
            this.Notification.WarningOptions.CloseIconColor = System.Drawing.Color.White;
            this.Notification.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.Notification.WarningOptions.ForeColor = System.Drawing.Color.White;
            this.Notification.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.Notification.WarningOptions.IconLeftMargin = 12;
            this.Notification.ZoomCloseIcon = true;
            // 
            // ContentInteractionPanel
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(48)))), ((int)(((byte)(71)))), ((int)(((byte)(94)))));
            this.ClientSize = new System.Drawing.Size(926, 307);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "ContentInteractionPanel";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Артикул";
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel LabelHeader;
        private Bunifu.UI.WinForms.BunifuTextBox TextBoxTitle;
        private Bunifu.UI.WinForms.BunifuTextBox TextBoxQuantity;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ButtonCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ButtonSave;
        private Bunifu.UI.WinForms.BunifuLabel LabelPrice;
        private Bunifu.UI.WinForms.BunifuLabel LabelQuantity;
        private Bunifu.UI.WinForms.BunifuLabel LabelTitle;
        private Bunifu.UI.WinForms.BunifuLabel LabelTotalSum;
        private Bunifu.UI.WinForms.BunifuTextBox TextBoxTotalSum;
        private Bunifu.UI.WinForms.BunifuSnackbar Notification;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton ButtonDelete;
        private Bunifu.UI.WinForms.BunifuTextBox TextBoxPrice;
    }
}